const $=id=>document.getElementById(id);
const state={key:'',connected:false,rows:[],regions:{},network:{},models:[],saved:{},selected:new Set(),region:'all',filter:'all',query:'',epoch:0,modelSeq:0,detail:null,job:null,login:null,loginRegion:'cn',request:null};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const text=(tag,value,className)=>{const e=document.createElement(tag);if(value!==undefined)e.textContent=value;if(className)e.className=className;return e;};
const money=n=>Number(n).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const regionName=r=>r==='cn'?'国内版':'国际版';
const accountName=r=>r.account?.nickname||r.account?.name||r.account?.uid||r.id;
function relativeDate(value){if(!value)return '尚未查询';const delta=Math.max(0,Date.now()-new Date(value).getTime());if(delta<60000)return '刚刚';if(delta<3600000)return Math.floor(delta/60000)+' 分钟前';if(delta<86400000)return Math.floor(delta/3600000)+' 小时前';return new Date(value).toLocaleDateString('zh-CN');}
function badge(label,style='neutral'){return text('span',label,'badge '+style);}
function toast(message,style='success'){const n=text('div',message,'toast '+style);$('toasts').append(n);setTimeout(()=>n.remove(),5000);}
function notice(message,error=false){$('notice').textContent=message;$('notice').classList.toggle('error',error);$('notice').hidden=!message;}
function describeError(e){if(!e)return '';if(e.risk?.action)return e.risk.action;if(e.code==='upstream_connection_error')return '连接失败，请检查系统代理或网络';if(e.code==='login_required'||e.code==='invalid_api_key')return '登录已失效，请重新连接';return e.message||e.code||'请求失败';}
async function api(path,{method='GET',body,signal,silent=false}={}){const headers={'Content-Type':'application/json','X-WB-UI':'1'};if(state.key)headers.Authorization='Bearer '+state.key;const response=await fetch(path,{method,credentials:'same-origin',headers,body:body===undefined?undefined:JSON.stringify(body),signal});let data;try{data=await response.json();}catch{throw Error('服务返回了非 JSON 数据');}if(!response.ok){const error=Error(data.error?.message||('HTTP '+response.status));error.risk=data.error?.risk;error.code=data.error?.code;error.status=response.status;if(response.status===401&&state.connected&&!silent&&!String(data.error?.code??'').startsWith('risk_')&&data.error?.code!=='login_required'){showAuth();$('auth-error').textContent='管理会话已过期，请重新连接。上游账号登录仍保留。';}throw error;}return data;}
async function run(button,fn){if(button.disabled)return;button.disabled=true;button.setAttribute('aria-busy','true');try{await fn();}catch(e){if(e.name!=='AbortError')toast(describeError(e),'error');}finally{button.disabled=false;button.removeAttribute('aria-busy');}}
function on(id,fn){$(id).addEventListener('click',()=>run($(id),fn));}
function action(label,fn,className=''){const b=text('button',label,className);b.type='button';b.addEventListener('click',e=>{e.stopPropagation();run(b,fn);});return b;}
function option(select,value,label){const o=text('option',label);o.value=value;select.append(o);}
const titles={accounts:'账号',pricing:'模型倍率',logs:'调用记录',keys:'API Keys'};
function route(name){if(!titles[name])name='accounts';for(const p of document.querySelectorAll('[data-page]'))p.hidden=p.dataset.page!==name;for(const b of document.querySelectorAll('[data-route]')){const active=b.dataset.route===name;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}$('crumb').textContent=titles[name];$('page-title').textContent=titles[name];document.title='WB Gateway · '+titles[name];if(location.hash!=='#'+name)history.replaceState(null,'','#'+name);if(name==='pricing'&&state.connected)loadPricing().catch(e=>toast(describeError(e),'error'));if(name==='logs'&&state.connected)loadLogs().catch(e=>toast(describeError(e),'error'));if(name==='keys'&&state.connected)loadKeys().catch(e=>toast(describeError(e),'error'));}
for(const b of document.querySelectorAll('[data-route]'))b.addEventListener('click',()=>route(b.dataset.route));
window.addEventListener('hashchange',()=>route(location.hash.slice(1)));
function showAuth(){state.connected=false;state.epoch++;state.key='';state.modelSeq++;state.request?.abort();$('workspace').hidden=true;$('auth').hidden=false;for(const d of document.querySelectorAll('dialog[open]'))d.close();state.rows=[];state.models=[];state.saved={};state.selected.clear();$('accounts').replaceChildren();$('key').value='';$('new-api-key').value='';$('api-key-list').replaceChildren();logRows=[];logPage=1;logSequence++;$('logs-rows').replaceChildren();$('logs-stats').replaceChildren();$('log-detail').replaceChildren();resetPricing();}
async function connect(){state.connected=true;state.epoch++;$('auth').hidden=true;$('workspace').hidden=false;$('auth-error').textContent='';$('key').value='';state.key='';route(location.hash.slice(1)||'accounts');await dashboard();if(state.rows.some(r=>!r.management?.balance?.updated_at||Date.now()-new Date(r.management.balance.updated_at).getTime()>60000))runBulk('refresh',state.rows.map(r=>r.id),true).catch(e=>toast(describeError(e),'error'));}
function filtered(){return state.rows.filter(r=>(state.region==='all'||r.region===state.region)&&(!state.query||(accountName(r)+' '+r.id+' '+(r.account?.uid??'')).toLowerCase().includes(state.query))&&(state.filter==='all'||state.filter==='error'&&(!r.management?.balance||r.management.balance.error)||state.filter==='ready'&&r.management?.checkin?.active&&!r.management.checkin.today_checked_in&&!r.management.checkin.error));}
function checkinState(r){const m=r.management,c=m?.checkin;if(!c)return {label:'未查询',kind:'neutral'};if(c.error||c.stale)return {label:'状态未知',kind:'warning'};if(c.today_checked_in)return {label:'今日已签到',kind:'success'};if(m?.claim?.status==='outcome_unknown')return {label:'需核实上次结果',kind:'warning'};if(c.active)return {label:'可领取 '+(c.today_credit??'')+' 积分',kind:'violet'};return {label:'暂无签到资格',kind:'neutral'};}
function renderSummaries(){$('summaries').replaceChildren();for(const r of ['cn','intl']){const d=state.regions[r]??{accounts:0,known:0,unknown:0,stale:0},card=text('section',undefined,'summary-card'),title=text('div',undefined,'summary-title');title.append(text('span',r==='cn'?'CN':'GL','region-icon '+r),text('span',regionName(r)+' · 可用积分'));let amount=d.accounts===0?'0.00':d.known?money(d.known_subtotal):d.stale?money(d.cached_subtotal):'—';const value=text('div',amount,'summary-value');value.append(text('span',d.stale?'含缓存 / credits':'credits','unit'));const meta=text('div',undefined,'summary-meta');meta.append(text('span',d.accounts+' 个账号'),text('span',d.unknown?d.unknown+' 个待刷新':d.stale?d.stale+' 个缓存余额':'余额已同步','subtle-link'));if(d.stale&&d.known)value.firstChild.textContent=money(d.cached_subtotal);card.append(title,value,meta);$('summaries').append(card);}const total=state.rows.length,healthy=state.rows.filter(r=>r.management?.balance&&!r.management.balance.error).length,card=text('section',undefined,'summary-card'),title=text('div',undefined,'summary-title');title.append(text('span','●','region-icon all'),text('span','账户概况'));const value=text('div',String(total),'summary-value');value.append(text('span','个已登录账号','unit'));const meta=text('div',undefined,'summary-meta');meta.append(text('span',healthy+' 个余额可用'),text('span',total-healthy+' 个待同步'));card.append(title,value,meta);$('summaries').append(card);}
function renderSelection(){const targets=state.rows.filter(r=>state.region==='all'||r.region===state.region);$('checkin-all').textContent=state.region==='all'?'一键签到':'签到'+(state.region==='cn'?'国内':'国际');$('checkin-all').disabled=!targets.length||!!state.job;const visible=filtered(),chosen=visible.filter(r=>state.selected.has(r.id)).length;$('select-all').checked=visible.length>0&&chosen===visible.length;$('select-all').indeterminate=chosen>0&&chosen<visible.length;$('select-all').disabled=!visible.length;$('bulk-bar').hidden=!state.selected.size;$('selection-count').textContent='已选 '+state.selected.size+' 个账号';}
function renderAccounts(){const rows=filtered();$('accounts').replaceChildren();for(const r of rows){const tr=text('tr');tr.classList.toggle('selected',state.selected.has(r.id));const selection=text('td',undefined,'check-col'),checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=state.selected.has(r.id);checkbox.setAttribute('aria-label','选择 '+accountName(r));checkbox.addEventListener('change',()=>{if(checkbox.checked)state.selected.add(r.id);else state.selected.delete(r.id);tr.classList.toggle('selected',checkbox.checked);renderSelection();});selection.append(checkbox);const name=text('td'),cell=text('div',undefined,'account-cell'),avatar=text('span',accountName(r).slice(0,1).toUpperCase(),'avatar '+r.region),copy=text('div');copy.append(text('span',accountName(r),'account-title'),text('span',r.id.length>20?r.id.slice(0,20)+'…':r.id,'account-sub'));cell.append(avatar,copy);name.append(cell);const region=text('td');region.append(badge(regionName(r.region),r.region==='cn'?'violet':'blue'));const balance=text('td'),b=r.management?.balance;balance.append(text('span',b?.unlimited?'不限额':typeof b?.remaining==='number'?money(b.remaining):'—','balance-number'));if(b?.stale||b?.error)balance.append(text('span',typeof b.remaining==='number'?'上次成功余额 · 刷新失败':'查询失败','balance-caption'));else if(typeof b?.remaining==='number'&&b.total>0){const meter=text('div',undefined,'credit-meter'),progress=document.createElement('progress');progress.max=b.total;progress.value=Math.max(0,Math.min(b.remaining,b.total));progress.setAttribute('aria-label','剩余积分');meter.append(progress);balance.append(meter);}else if(!b)balance.append(text('span','等待同步','balance-caption'));const sign=text('td'),c=checkinState(r);sign.append(badge(c.label,c.kind));if(r.restrictions?.length)sign.append(badge('请求已暂停','warning'));const update=text('td',relativeDate(b?.updated_at??(b&&!b.error?r.management?.updated_at:null)));const ops=text('td',undefined,'align-right');ops.append(action('详情',()=>showDetails(r.id)),action('↻',async()=>{const result=await api('/admin/accounts/'+r.id+'/balance',{method:'POST',body:{}});await dashboard();if(result.balance?.error)throw Error(result.balance.error.message??'余额查询失败');toast('余额刷新完成');},'quiet'));ops.lastChild.setAttribute('aria-label','刷新 '+accountName(r));tr.append(selection,name,region,balance,sign,update,ops);$('accounts').append(tr);}$('empty').hidden=rows.length>0;$('empty-title').textContent=state.rows.length?'没有匹配的账号':'暂无账号';$('empty-description').textContent=state.rows.length?'试试其他地区或搜索条件。':'添加账号开始使用。';$('empty-add').hidden=state.rows.length>0;$('table-count').textContent='显示 '+rows.length+' / '+state.rows.length+' 个账号';$('all-count').textContent=state.rows.length;$('nav-count').textContent=state.rows.length;renderSelection();}
async function dashboard(){const epoch=state.epoch,d=await api('/admin/dashboard');if(epoch!==state.epoch)return;state.restrictions=d.restrictions??[];renderRisk();state.rows=d.accounts;state.regions=d.regions;state.network=d.network??{};for(const id of state.selected)if(!state.rows.some(r=>r.id===id))state.selected.delete(id);renderSummaries();renderAccounts();renderNetwork();if(state.detail&&$('account-dialog').open)renderDetails();}
function renderNetwork(){const n=state.network,source={windows_system:'Windows 系统代理',environment:'环境变量代理',direct:'直接连接',unconfigured:'自定义 / 未配置'}[n.source]??'未获取';$('network-pill').textContent='网络 · '+source;$('network-pill').className='badge '+(n.source==='windows_system'||n.source==='environment'?'success':'neutral');}
function renderDetails(){const r=state.rows.find(r=>r.id===state.detail);if(!r){$('account-dialog').close();return;}$('detail-name').textContent=accountName(r);const box=$('detail-content');box.replaceChildren();box.append(badge(regionName(r.region),r.region==='cn'?'violet':'blue'));const b=r.management?.balance,credit=text('div',undefined,'detail-credit');credit.append(text('span',b?.stale?'上次成功查询的余额':'当前可用积分'),text('strong',b?.unlimited?'不限额':typeof b?.remaining==='number'?money(b.remaining):'—'),text('p',b?.updated_at?'更新于 '+new Date(b.updated_at).toLocaleString('zh-CN'):'尚未成功查询'));if(b?.error)credit.append(text('p',describeError(b.error),'error-text'));box.append(credit);for(const restriction of r.restrictions??[])box.append(text('p',restriction.action,'callout'));const dl=text('dl',undefined,'detail-list');const c=checkinState(r);for(const [label,value]of [['账号 ID',r.id],['总额度',b?.total!=null?money(b.total):'—'],['已使用',b?.used!=null?money(b.used):'—'],['签到状态',c.label],['登录有效期',r.expires_at?new Date(r.expires_at).toLocaleString('zh-CN'):'上游未提供']]){const row=text('div');row.append(text('dt',label),text('dd',value));dl.append(row);}box.append(dl,action('复制 API 账号 ID',async()=>{await navigator.clipboard.writeText(r.id);toast('账号 ID 已复制');},'text-button'));if(r.management?.checkin?.error)box.append(text('p',describeError(r.management.checkin.error),'callout'));$('detail-checkin').disabled=!!r.restrictions?.length||!r.management?.checkin?.active||r.management.checkin.today_checked_in||!!r.management.checkin.error||r.management?.claim?.status==='outcome_unknown';}
async function showDetails(id){state.detail=id;renderDetails();if(!$('account-dialog').open)$('account-dialog').showModal();const record=state.rows.find(r=>r.id===id);if(!record?.management?.checkin){await api('/admin/accounts/'+id+'/inspect',{method:'POST',body:{}});await dashboard();if(state.detail===id)renderDetails();}}
let confirmResolver=null;
function confirmAction(title,message,button='确认'){return new Promise(resolve=>{confirmResolver=resolve;$('confirm-title').textContent=title;$('confirm-text').textContent=message;$('confirm-ok').textContent=button;$('confirm-dialog').showModal();});}
function finishConfirm(value){const resolve=confirmResolver;confirmResolver=null;$('confirm-dialog').close();resolve?.(value);}
$('confirm-ok').addEventListener('click',()=>finishConfirm(true));$('confirm-cancel').addEventListener('click',()=>finishConfirm(false));$('confirm-dialog').addEventListener('cancel',()=>{confirmResolver?.(false);confirmResolver=null;});
async function runBulk(actionName,ids,quiet=false){ids=[...new Set(ids)].filter(id=>state.rows.some(r=>r.id===id)).sort();if(!ids.length)return;if(state.job){if(!quiet)toast('已有批量任务运行中，请等待完成。','info');return;}const epoch=state.epoch;state.job={id:null};renderSelection();$('job-panel').hidden=false;$('job').textContent='正在创建任务…';$('job-progress').value=0;try{let job=await api('/admin/jobs',{method:'POST',body:{action:actionName,account_ids:ids}});state.job=job;while(epoch===state.epoch){$('job').textContent=(actionName==='refresh'?'同步余额':'官方签到')+' · '+job.completed+'/'+job.total;$('job-progress').value=job.total?job.completed/job.total*100:100;if(job.status==='completed'){await dashboard();const failed=job.results.filter(x=>x.error||x.result?.balance?.error&&actionName==='refresh'||x.result?.checkin?.error&&actionName==='checkin'||x.result?.claim?.error&&actionName==='checkin').length;const skipped=job.results.filter(x=>!x.error&&!x.result?.checkin?.error&&!x.result?.claim?.error&&['not_eligible','already_claimed','outcome_unknown'].includes(x.result?.claim?.status)).length;if(!quiet||failed)toast(actionName==='refresh'?'余额同步完成：'+(job.completed-failed)+' 个成功，'+failed+' 个异常':'签到完成：'+(job.completed-failed-skipped)+' 个成功，'+skipped+' 个跳过，'+failed+' 个异常',failed?'error':'success');break;}await sleep(600);job=await api('/admin/jobs/'+job.id);}}finally{state.job=null;renderSelection();$('job-panel').hidden=true;}}
function openLogin(){if(state.login){$('login-dialog').showModal();return;}$('login').hidden=true;$('create-login').hidden=false;for(const b of document.querySelectorAll('[data-login-region]'))b.disabled=false;$('login-dialog').showModal();}
async function cancelLogin(){const id=state.login?.id;state.login=null;$('login').hidden=true;$('create-login').hidden=false;for(const b of document.querySelectorAll('[data-login-region]'))b.disabled=false;if(id&&state.connected)await api('/admin/login/'+id,{method:'DELETE',silent:true}).catch(()=>{});}
async function createLogin(){const epoch=state.epoch,data=await api('/admin/login',{method:'POST',body:{region:state.loginRegion}});if(epoch!==state.epoch)return;state.login={id:data.login_id,expires:data.expires_at};$('create-login').hidden=true;$('login').hidden=false;$('login-link').href=data.auth_url;$('login-status').textContent='点击下方链接，在官方页面完成授权。';for(const b of document.querySelectorAll('[data-login-region]'))b.disabled=true;try{while(state.login?.id===data.login_id&&epoch===state.epoch){await sleep(Math.max(data.interval_ms??1000,1000));if(state.login?.id!==data.login_id||epoch!==state.epoch)return;const result=await api('/admin/login/'+data.login_id);if(result.status==='complete'){state.login=null;$('login-dialog').close();await dashboard();route('accounts');toast('登录成功，账号已加密保存');api('/admin/accounts/'+result.account_id+'/inspect',{method:'POST',body:{}}).then(dashboard).catch(e=>toast(describeError(e),'error'));return;}}}catch(e){await cancelLogin();throw e;}}
on('unlock',async()=>{state.key=$('key').value.trim();if(!state.key){$('auth-error').textContent='请输入管理密钥';return;}try{await api('/admin/session',{method:'POST',body:{},silent:true});await connect();}catch(e){state.key='';$('auth-error').textContent=describeError(e);throw e;}});
$('key').addEventListener('keydown',e=>{if(e.key==='Enter')$('unlock').click();});
async function lock(){await cancelLogin();await api('/admin/session',{method:'DELETE',silent:true}).catch(()=>{});showAuth();toast('控制台已锁定，上游账号登录仍保留。','info');}
on('lock',lock);on('add-account',async()=>openLogin());on('empty-add',async()=>openLogin());on('create-login',createLogin);on('cancel-login',cancelLogin);
for(const b of document.querySelectorAll('[data-login-region]'))b.addEventListener('click',()=>{state.loginRegion=b.dataset.loginRegion;for(const x of document.querySelectorAll('[data-login-region]'))x.classList.toggle('selected',x===b);});
for(const b of document.querySelectorAll('[data-close]'))b.addEventListener('click',async()=>{const id=b.dataset.close;if(id==='login-dialog')await cancelLogin();$(id).close();});
$('login-dialog').addEventListener('cancel',()=>cancelLogin());
for(const b of document.querySelectorAll('[data-region]'))b.addEventListener('click',()=>{state.region=b.dataset.region;state.selected.clear();for(const x of document.querySelectorAll('[data-region]'))x.classList.toggle('selected',x===b);renderAccounts();});
$('search').addEventListener('input',()=>{state.query=$('search').value.trim().toLowerCase();state.selected.clear();renderAccounts();});$('balance-filter').addEventListener('change',()=>{state.filter=$('balance-filter').value;state.selected.clear();renderAccounts();});
$('select-all').addEventListener('change',()=>{for(const r of filtered())if($('select-all').checked)state.selected.add(r.id);else state.selected.delete(r.id);renderAccounts();});
on('checkin-all',async()=>{const ids=state.rows.filter(r=>state.region==='all'||r.region===state.region).map(r=>r.id);if(!ids.length)return;const cn=state.rows.filter(r=>ids.includes(r.id)&&r.region==='cn').length;if(await confirmAction('一键签到'+(state.region==='all'?'全部账号':regionName(state.region))+'？','将查询并签到 '+ids.length+' 个账号（国内 '+cn+' / 国际 '+(ids.length-cn)+'）。范围按地区选择，不受搜索或状态筛选影响。今日已签、活动未开放会跳过；遇到风控不会绕过。','确认签到'))await runBulk('checkin',ids);});
on('clear-selection',async()=>{state.selected.clear();renderAccounts();});on('refresh',()=>runBulk('refresh',filtered().map(r=>r.id)));on('bulk-refresh',()=>runBulk('refresh',[...state.selected]));on('checkin',async()=>{const ids=[...state.selected];if(!ids.length)return;const cn=state.rows.filter(r=>ids.includes(r.id)&&r.region==='cn').length;if(await confirmAction('为选中账号签到？','仅操作 '+ids.length+' 个勾选账号（国内 '+cn+' / 国际 '+(ids.length-cn)+'）。不符合资格或今日已签会跳过。','确认签到'))await runBulk('checkin',ids);});
on('detail-refresh',async()=>{const result=await api('/admin/accounts/'+state.detail+'/inspect',{method:'POST',body:{}});await dashboard();if(result.balance?.error)throw Error(describeError(result.balance.error));toast('账号余额与状态已更新');});
on('detail-checkin',async()=>{const id=state.detail;if(await confirmAction('确认官方签到？','仅为当前账号签到，不自动重试不确定的结果。','确认签到')){await api('/admin/accounts/'+id+'/checkin',{method:'POST',body:{}});await dashboard();const m=state.rows.find(r=>r.id===id)?.management;if(m?.claim?.error||m?.checkin?.error)throw Error(describeError(m.claim?.error??m.checkin?.error));toast(m?.claim?.status==='claimed'?'签到成功，获得 '+m.claim.credit+' 积分':checkinState(state.rows.find(r=>r.id===id)).label);}});
on('detail-remove',async()=>{const id=state.detail,r=state.rows.find(r=>r.id===id);if(await confirmAction('移除本地账号？','将删除「'+accountName(r)+'」的本地登录与配置。官方会话不会被撤销。','确认移除')){await api('/admin/accounts/'+id,{method:'DELETE'});state.selected.delete(id);$('account-dialog').close();state.detail=null;await dashboard();toast('本地账号已移除');}});
setInterval(()=>{if(state.connected&&!document.hidden&&$('auto-refresh').checked&&!state.job&&state.rows.length)runBulk('refresh',state.rows.map(r=>r.id),true).catch(()=>{});},60000);
(async()=>{try{await api('/admin/session',{silent:true});await connect();}catch{showAuth();}})();
const scopeLabel=scope=>({all:'全部区域',cn:'仅国内版',intl:'仅国际版'}[scope]??scope);
async function loadKeys(){const epoch=state.epoch;const data=await api('/admin/keys');if(epoch!==state.epoch||!state.connected)return;$('api-base').value=location.origin+'/v1';$('legacy-key-warning').hidden=!data.legacy_api_key_enabled;$('key-count').textContent=data.keys.length+' 个';$('api-keys-empty').hidden=data.keys.length>0;const list=$('api-key-list');list.replaceChildren();for(const k of data.keys){const row=text('article',undefined,'api-key-card'),head=text('div',undefined,'api-key-head'),title=text('div');title.append(text('strong',k.name),text('code',k.prefix+'…'));const expired=k.expires_at&&Date.parse(k.expires_at)<=Date.now();head.append(title,badge(expired?'已过期':k.enabled?'使用中':'已禁用',expired?'warning':k.enabled?'success':'neutral'));const info=text('div',undefined,'api-key-meta');info.append(badge(scopeLabel(k.scope),'violet'),text('span',k.expires_at?'到期 '+new Date(k.expires_at).toLocaleDateString('zh-CN'):'不过期'),text('span',k.last_used_at?'最近使用 '+relativeDate(k.last_used_at):'尚未使用'));const controls=text('div',undefined,'api-key-actions');controls.append(action(k.enabled?'禁用':'启用',async()=>{await api('/admin/keys/'+k.id,{method:'POST',body:{enabled:!k.enabled}});await loadKeys();toast(k.enabled?'Key 已禁用':'Key 已启用');},'secondary'),action('撤销',async()=>{if(await confirmAction('撤销这个 Key？','「'+k.name+'」将永久失效，使用它的客户端需要换新 Key。账号登录不受影响。','确认撤销')){await api('/admin/keys/'+k.id,{method:'DELETE'});await loadKeys();toast('Key 已撤销');}},'danger-outline'));row.append(head,info,controls);list.append(row);}}
on('reload-keys',loadKeys);
on('copy-base',async()=>{await navigator.clipboard.writeText($('api-base').value);toast('API 地址已复制');});
on('create-api-key',async()=>{const name=$('api-key-name').value.trim();if(!name)throw Error('请给 Key 填写一个名称');const days=Number($('api-key-expiry').value);const data=await api('/admin/keys',{method:'POST',body:{name,scope:$('api-key-scope').value,expires_at:days?new Date(Date.now()+days*86400000).toISOString():null}});$('new-api-key').value=data.key;$('new-api-key-scope').textContent=scopeLabel(data.scope)+' · API Base URL: '+location.origin+'/v1';$('key-created-dialog').showModal();$('api-key-name').value='';await loadKeys();});
on('copy-new-key',async()=>{await navigator.clipboard.writeText($('new-api-key').value);toast('Key 已复制，请粘贴到客户端');});
$('key-created-dialog').addEventListener('close',()=>{$('new-api-key').value='';});

function renderRisk(){
 const entries=state.restrictions??[];$('risk-panel').hidden=!entries.length;$('risk-list').replaceChildren();
 const labels={ip_restricted:'IP 限制',device_verification:'设备 / 人机验证',rate_limited:'请求限流',login_required:'需要重新登录',permission_denied:'权限被拒绝',enterprise_quota:'企业创建配额',quota_exhausted:'积分 / 配额不足',upstream_unavailable:'上游暂不可用'};
 for(const e of entries){const row=text('article',undefined,'risk-entry');row.append(text('strong',(e.scope==='global'?'两区共同暂停':regionName(e.region))+' · '+(labels[e.kind]??e.kind)),text('p',e.action));const remaining=Math.max(0,Math.ceil((e.retry_at-Date.now())/1000));row.append(text('small',(remaining?'最早可重试：'+new Date(e.retry_at).toLocaleString('zh-CN'):'冷却已结束')+(e.manual?' · 仍需人工处理':' · 不会自动重放'), 'muted'));if(e.request_id)row.append(text('small','请求 ID：'+e.request_id,'muted'));if(e.kind==='login_required')row.append(text('p','请使用「添加账号」重新授权原账号；成功后自动解除登录暂停。','muted'));else if(e.manual){const button=action('已处理，恢复请求',async()=>{if(await confirmAction('确认恢复本地请求？','请先完成官方验证或权限 / 配额处理。这里只移除本地暂停，不会解除官方限制，也不会重放失败的生成或签到。','确认已处理')){await api('/admin/risk/'+e.id+'/resume',{method:'POST',body:{official_issue_resolved:true}});await dashboard();}},'secondary');button.disabled=remaining>0;row.append(button);}$('risk-list').append(row);}
}
on('risk-refresh',dashboard);
let logPage=1,logSequence=0,logRows=[];
const duration=v=>v==null?'—':v<1000?Math.round(v)+' ms':(v/1000).toFixed(2)+' s';
const byteSize=v=>v<1024?v+' B':v<1048576?(v/1024).toFixed(1)+' KB':(v/1048576).toFixed(2)+' MB';
async function loadLogs(){
 const sequence=++logSequence,epoch=state.epoch,query=new URLSearchParams({page:String(logPage),limit:'25',model:$('logs-model').value.trim()});for(const part of ['region','status']){const value=$('logs-'+part).value;if(value&&value!=='all')query.set(part,value);}for(const part of ['from','to'])if($('logs-'+part).value)query.set(part,new Date($('logs-'+part).value).toISOString());
 const d=await api('/admin/call-logs?'+query);if(sequence!==logSequence||epoch!==state.epoch)return;logRows=d.data;const stats=$('logs-stats');stats.replaceChildren();for(const [label,value,caption]of [['请求次数',d.summary.requests+'','当前筛选范围'],['已确认积分',d.summary.known_credit.toFixed(4),d.summary.credit_known+' 条已返回 · '+d.summary.credit_unknown+' 条未提供'],['请求流量',byteSize(d.summary.request_bytes),'JSON 请求体累计大小']]){const card=text('article',undefined,'log-stat');card.append(text('span',label,'muted'),text('strong',value),text('small',caption,'muted'));stats.append(card);}
 $('logs-rows').replaceChildren();for(const r of logRows){const tr=text('tr');const at=text('td',new Date(r.started_at).toLocaleString('zh-CN'));at.append(text('small',r.region?regionName(r.region):'尚未选择账号','log-secondary'));const model=text('td',r.model??r.requested_model??'—','log-model');if(r.upstream_model&&r.upstream_model!==r.model)model.append(text('small','上游：'+r.upstream_model,'log-secondary'));const status=text('td');status.append(badge({completed:'成功',failed:'失败',cancelled:'已取消'}[r.outcome]??r.outcome,r.outcome==='completed'?'success':r.outcome==='failed'?'warning':'neutral'));const first=text('td',duration(r.first_text_ms));first.append(text('small','首 Token '+duration(r.first_token_ms),'log-secondary'));const ops=text('td');ops.append(action('详情',()=>showLog(r.id),'text-button'));tr.append(at,model,status,text('td',byteSize(r.request_bytes)),text('td',r.credit==null?'未提供':r.credit.toFixed(4)),text('td',r.request_ip??'—','log-ip'),first,text('td',duration(r.reasoning_ms)),text('td',duration(r.duration_ms)),ops);const labels=['时间 / 地区','模型','状态','请求大小','积分','请求 IP','首字 / 首 Token','思考','总耗时',''];for(let i=0;i<tr.children.length;i++)tr.children[i].dataset.label=labels[i];$('logs-rows').append(tr);}
 $('logs-empty').hidden=!!logRows.length;$('logs-count').textContent=d.total+' 条记录';$('logs-page').textContent=logPage+' / '+Math.max(1,Math.ceil(d.total/d.limit));$('logs-prev').disabled=logPage<=1;$('logs-next').disabled=logPage*d.limit>=d.total;$('logs-warning').hidden=!d.storage_error;$('logs-warning').textContent=d.storage_error??'';
}
function showLog(id){const r=logRows.find(x=>x.id===id);if(!r)return;const out=$('log-detail');out.replaceChildren();for(const [name,value]of [['请求 ID',r.id],['请求时间',r.started_at],['接口',r.endpoint],['请求模型',r.requested_model],['实际路由模型',r.model],['上游返回模型',r.upstream_model],['地区',r.region?regionName(r.region):null],['账号 ID',r.account_id],['API Key ID',r.api_key_id],['请求 IP',r.request_ip],['请求大小',r.request_bytes+' bytes'],['HTTP 状态',r.status_code],['调用状态',r.outcome],['错误码',r.error_code],['流式',r.stream?'是':'否'],['输入 Token',r.input_tokens],['输出 Token',r.output_tokens],['思考 Token',r.reasoning_tokens],['花费积分',r.credit],['积分来源',r.credit_source==='upstream_usage.credit'?'上游 usage.credit':'上游未返回'],['首字时间',duration(r.first_text_ms)],['首 Token 时间',duration(r.first_token_ms)],['思考耗时',duration(r.reasoning_ms)],['思考计时依据',r.reasoning_timing_source?'流式思考片段观测，非内部精确耗时':'未观测到思考片段'],['总耗时',duration(r.duration_ms)]]){const row=text('div');row.append(text('dt',name),text('dd',value??'—'));out.append(row);}$('log-dialog').showModal();}
$('logs-filter').addEventListener('submit',e=>{e.preventDefault();logPage=1;loadLogs().catch(e=>toast(describeError(e),'error'));});
on('logs-refresh',loadLogs);
$('logs-prev').addEventListener('click',()=>{if(logPage>1){logPage--;loadLogs().catch(e=>toast(describeError(e),'error'));}});
$('logs-next').addEventListener('click',()=>{logPage++;loadLogs().catch(e=>toast(describeError(e),'error'));});
const PRICING_REFRESH_MS=30*60*1000;
const pricingState={region:'cn',account:'',data:null,error:'',sequence:0,controller:null,loading:false,cache:new Map(),inflight:new Map(),timer:null,renderSignature:null};
const pricingKey=()=>JSON.stringify([pricingState.region,pricingState.account]);
const pricingSignature=d=>JSON.stringify(d,(k,v)=>k==='fetched_at'||k==='server_time'?undefined:v);
function resetPricing(){for(const p of pricingState.inflight.values())p.controller.abort();pricingState.inflight.clear();pricingState.cache.clear();clearTimeout(pricingState.timer);clearTimeout(pricingState.expiryTimer);pricingState.accountsSignature=null;pricingState.account='';pricingState.data=null;pricingState.error='';pricingState.loading=false;pricingState.renderSignature=null;$('pricing-rows').replaceChildren();$('pricing-account').replaceChildren();$('pricing-empty').hidden=false;}
function pricingWarning(){const warnings=[];if(pricingState.error)warnings.push((pricingState.data?'刷新失败，保留上次数据 · ':'')+pricingState.error);const d=pricingState.data;if(d?.errors?.length)warnings.push(d.errors.length+' 个账号获取失败');const missing=(d?.models??[]).filter(m=>m.variants.some(q=>q.status!=='provided')).length;if(missing)warnings.push('官方未提供 '+missing+' 个模型的数值倍率');const label=warnings.join(' · '),el=$('pricing-warning');if(el.hidden!==!warnings.length)el.hidden=!warnings.length;if(el.textContent!==label)el.textContent=label;}
function schedulePricingRefresh(){clearTimeout(pricingState.timer);const entry=pricingState.cache.get(pricingKey());if(!state.connected||document.hidden||!$('pricing-auto').checked||!entry||pricingState.inflight.has(pricingKey()))return;pricingState.timer=setTimeout(()=>{if(state.connected&&!document.hidden&&$('pricing-auto').checked)loadPricing({force:true}).catch(()=>{});},Math.max(0,entry.checkedAt+PRICING_REFRESH_MS-Date.now()));}
$('theme-mode').value=window.WBTheme?.get()??'system';
$('theme-mode').addEventListener('change',()=>window.WBTheme?.set($('theme-mode').value));
window.addEventListener('wb-theme-change',()=>{$('theme-mode').value=window.WBTheme?.get()??'system';});
const multiplierText=n=>Number.isFinite(n)?n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:6})+'×':'未提供';
function paintPricing(){
 const d=pricingState.data,container=$('pricing-rows'),query=$('pricing-search').value.trim().toLowerCase();container.replaceChildren();const models=(d?.models??[]).filter(m=>!query||(m.id+' '+m.name).toLowerCase().includes(query));$('pricing-count').textContent=models.length+' 个模型';
 for(const m of models){const groups=new Map();for(const q of m.variants){const signature=JSON.stringify([q.credits_raw,q.base_multiplier,q.effective_multiplier,q.status,q.promotion]);const group=groups.get(signature)??{quote:q,accounts:[]};group.accounts.push(q.account_name);groups.set(signature,group);}for(const {quote:q,accounts}of groups.values()){const tr=text('tr'),model=text('td'),current=text('td'),original=text('td'),promo=text('td'),account=text('td');model.append(text('span',m.name),text('code',m.id,'model-id'));const expired=q.promotion?.valid_until&&Date.parse(q.promotion.valid_until)<=Date.now();const value=expired?'待刷新':q.status==='provided'?multiplierText(q.effective_multiplier):q.status==='unparsed'?q.credits_raw:'未提供';current.append(text('span',value,q.status==='provided'&&!expired?'multiplier':'price-unknown'));current.title='来源：'+q.source+(q.credits_raw?' · 原始值：'+q.credits_raw:'');original.append(text('span',q.base_multiplier===null?'—':multiplierText(q.base_multiplier),'price-base'));if(q.promotion){promo.append(text('span',expired?'活动已结束':q.promotion.label||'限时活动','price-promotion'));if(q.promotion.valid_until)promo.append(text('small',new Date(q.promotion.valid_until).toLocaleDateString('zh-CN')+' 截止','quote-expiry'));}else promo.textContent='—';account.textContent=accounts.length===d.accounts.length&&accounts.length>1?'全部 · '+accounts.length+' 个账号':accounts.join('、');account.title=accounts.join('、');tr.append(model,current,original,promo,account);container.append(tr);}}
 $('pricing-empty').hidden=models.length>0;$('pricing-empty').textContent=pricingState.loading?'正在获取…':!d?'获取失败，请重试':d.status==='no_accounts'?'该地区暂无登录账号':d.status==='unavailable'?'当前无法获取，请检查账号状态':query?'没有匹配的模型':'暂无可用模型';const missing=(d?.models??[]).filter(m=>m.variants.some(q=>q.status!=='provided')).length;const warnings=pricingState.error?[pricingState.error]:[];if(d?.errors?.length)warnings.push(d.errors.length+' 个账号获取失败');if(missing)warnings.push('官方未提供 '+missing+' 个模型的数值倍率');$('pricing-warning').hidden=!warnings.length;$('pricing-warning').textContent=warnings.join(' · ');$('pricing-warning').title=(d?.errors??[]).map(e=>e.code+': '+e.message).join('; ');$('pricing-updated').textContent=d?.fetched_at?new Date(d.fetched_at).toLocaleTimeString('zh-CN',{hour12:false})+' 更新':pricingState.loading?'获取中…':'未更新';$('pricing-source').textContent=d?.fetched_at?regionName(d.region)+' · 官方实时配置':'官方账号配置';
}
function showPricingEntry(entry){pricingState.data=entry?.data??null;pricingState.error=entry?.error??'';pricingState.loading=pricingState.inflight.has(pricingKey());const accounts=entry?.data?.accounts??pricingState.cache.get(JSON.stringify([pricingState.region,'']))?.data?.accounts??[];const signature=JSON.stringify([pricingState.region,accounts]);if(signature!==pricingState.accountsSignature){pricingState.accountsSignature=signature;const select=$('pricing-account');select.replaceChildren();option(select,'','全部账号');for(const a of accounts)option(select,a.id,a.name);}if($('pricing-account').value!==pricingState.account)$('pricing-account').value=pricingState.account;renderPricing();}
function renderPricing(){const signature=JSON.stringify([pricingKey(),pricingSignature(pricingState.data),$('pricing-search').value.trim().toLowerCase(),!pricingState.data&&pricingState.loading,(pricingState.data?.models??[]).map(m=>m.variants.map(q=>!!(q.promotion?.valid_until&&Date.parse(q.promotion.valid_until)<=Date.now())))]);if(signature!==pricingState.renderSignature){pricingState.renderSignature=signature;paintPricing();}pricingWarning();clearTimeout(pricingState.expiryTimer);const now=Date.now(),deadlines=(pricingState.data?.models??[]).flatMap(m=>m.variants.map(q=>Date.parse(q.promotion?.valid_until))).filter(t=>Number.isFinite(t)&&t>now);if(deadlines.length)pricingState.expiryTimer=setTimeout(()=>{if(state.connected)renderPricing();},Math.min(Math.min(...deadlines)-now+10,2147483647));}
async function loadPricing({force=false}={}){
 if(!state.connected)return;const key=pricingKey();let entry=pricingState.cache.get(key);const pending=pricingState.inflight.get(key);
 if(pending){showPricingEntry(entry);return pending.promise;}if(entry&&!force){showPricingEntry(entry);schedulePricingRefresh();return;}
 if(!entry){entry={data:null,signature:null,error:'',checkedAt:Date.now()};pricingState.cache.set(key,entry);}
 const epoch=state.epoch,params=new URLSearchParams({region:pricingState.region});if(pricingState.account)params.set('account_id',pricingState.account);const controller=new AbortController(),job={controller,promise:null};pricingState.inflight.set(key,job);clearTimeout(pricingState.timer);if(!entry.data)showPricingEntry(entry);
 job.promise=(async()=>{try{const d=await api('/admin/model-pricing?'+params,{signal:controller.signal});if(epoch!==state.epoch)return;if(entry.data&&d.errors?.length)throw Error(d.errors.map(e=>e.message||e.code).join(' · '));const signature=pricingSignature(d);if(signature!==entry.signature){entry.data=d;entry.signature=signature;}entry.error='';}
 catch(e){if(e.name==='AbortError'||epoch!==state.epoch)return;entry.error=describeError(e);throw e;}
 finally{if(epoch===state.epoch){entry.checkedAt=Date.now();pricingState.inflight.delete(key);if(key===pricingKey())showPricingEntry(entry);schedulePricingRefresh();}}})();return job.promise;
}
for(const button of document.querySelectorAll('[data-pricing-region]'))button.addEventListener('click',()=>{if(pricingState.region===button.dataset.pricingRegion)return;pricingState.region=button.dataset.pricingRegion;pricingState.account='';for(const b of document.querySelectorAll('[data-pricing-region]'))b.classList.toggle('selected',b===button);loadPricing().catch(()=>{});});
$('pricing-account').addEventListener('change',()=>{pricingState.account=$('pricing-account').value;loadPricing().catch(()=>{});});
$('pricing-search').addEventListener('input',renderPricing);
$('pricing-refresh').addEventListener('click',()=>loadPricing({force:true}).catch(()=>{}));
$('pricing-auto').addEventListener('change',schedulePricingRefresh);
document.addEventListener('visibilitychange',schedulePricingRefresh);

document.getElementById('sidebar-host').textContent=location.host;
